### ISSUE TITLE
Function example has extraneous semicolon.

### ISSUE THREAD

**Issue by corthon** [tianocore-docs/edk2-CCodingStandardsSpecification#1]
https://github.com/tianocore-docs/edk2-CCodingStandardsSpecification/blob/master/5_source_files/57_c_programming.md

Section 5.7.1.10, there is a semicolon after the function paramters. Probably a copy-paste error from the header file.

**Comment by ghost** [comment]
I've submitted a patch to fix this.

**Comment by mdkinney** [comment]
Tracking in Tianocore Bugzilla

https://bugzilla.tianocore.org/show_bug.cgi?id=1606
